
Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: "consistent_comma"

Metrics/BlockLength:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: "single_quotes"

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Lint/UnderscorePrefixedVariableName:
  Enabled: false
