# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# zmodload zsh/zprof

source ~/.antidote/antidote.zsh
# Tell zephyr where to put the compdump and to use caching
zstyle ':zephyr:plugin:completion' use-cache yes
antidote load
unset ZSH_AUTOSUGGEST_USE_ASYNC


# load global rc scripts

if [ -d /etc/profile.d ]; then
  for i in /etc/profile.d/*.(zsh|sh); do
    if [ -r $i ]; then
      . $i
    fi
  done
  unset i
fi

# zsh options & keybindings (after plugins, before tool integrations)
setopt NOTIFY PUSHD_TO_HOME BASH_AUTO_LIST LIST_AMBIGUOUS
setopt LONG_LIST_JOBS NO_CLOBBER
setopt PUSHD_SILENT AUTO_PUSHD PUSHD_MINUS
setopt EXTENDED_GLOB RC_QUOTES MAIL_WARNING

unsetopt BG_NICE AUTO_PARAM_SLASH MENU_COMPLETE AUTO_CD AUTO_RESUME GLOB_DOTS CORRECT CORRECT_ALL CDABLE_VARS AUTO_MENU
unsetopt REC_EXACT

unsetopt nomatch

setopt MENU_COMPLETE

# cd not select parent dir.
zstyle ':completion:*:cd:*' ignore-parents parent pwd

# fix forward delete
bindkey "^[[3~" delete-char

autoload -U up-line-or-beginning-search
autoload -U down-line-or-beginning-search
zle -N up-line-or-beginning-search
zle -N down-line-or-beginning-search
bindkey "^[[A" up-line-or-beginning-search # Up
bindkey "^[[B" down-line-or-beginning-search # Down

# Pre-rendered runtime config (generated by bin/df-compile)
[ -r ~/.tsi/rc.zsh ] && . ~/.tsi/rc.zsh

# zprof >! ~/.zprof.txt
