source "https://rubygems.org"

gem "activesupport", require: 'active_support/all'

gem "awesome_print"
gem "tty-table"
gem "paint"
gem "hashie"

gem "pry"

# gem "actionview"

gem "cri"
# gem "tty-prompt"
