# Don't print a new line at the start of the prompt
add_newline = false

[aws]
symbol = " "
disabled = true

[directory]
truncate_to_repo=false

#[line_break]
#disabled = true


[ruby]
format = "[$symbol$version]($style) "
symbol = " "

[battery]
full_symbol = ""
charging_symbol = ""
discharging_symbol = ""

[docker]
symbol = " "

[git_branch]
symbol = " "
format = "[$symbol$branch]($style) "

[golang]
symbol = " "

[memory_usage]
symbol = " "

[nim]
symbol = " "

[nodejs]
symbol = " "
format = "[$symbol$version]($style) "

[package]
symbol = " "
format = "[$symbol$version]($style) "
