ENV['BUNDLE_BUILD__NOKOGIRI'] = "--use-system-libraries"

source "https://rubygems.org"

gem "activesupport", require: 'active_support/all'
gem "actionview"

gem "cri"
gem "tty-prompt"
gem "tty-table"
